name: Test suite

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  test-full-project:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13-dev"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: pyproject.toml
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -e .[camera,database,dispatcher,test]
    - name: Test with pytest
      run: |
        pytest -v
